# Generated by Django 5.2.11 on 2026-02-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonprogress_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='vidost_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
