# Generated by Django 5.2.11 on 2026-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_vidost_url_course_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_gat',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-folder', max_length=50, null=True),
        ),
    ]
