# Generated by Django 5.2.11 on 2026-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_category_img_gat_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_gat',
            field=models.ImageField(blank=True, help_text='صورة تمثل التصنيف (يفضل 300x300 بكسل)', null=True, upload_to='category_images/', verbose_name='صورة التصنيف'),
        ),
    ]
