# Generated by Django 5.2.11 on 2026-02-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_category_img_gat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_gat',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='صورة التصنيف'),
        ),
    ]
