# Generated by Django 5.2.11 on 2026-02-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_category_img_gat'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, help_text='رفع ملف فيديو (mp4, webm, etc)', null=True, upload_to='courses/videos/', verbose_name='ملف فيديو'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو يوتيوب (مثال: https://www.youtube.com/watch?v=...)', null=True, verbose_name='رابط يوتيوب'),
        ),
    ]
