# Generated by Django 5.2.11 on 2026-02-17 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_video_file_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ نهاية الخصم'),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='نسبة الخصم (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم'),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بداية الخصم'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='مخفض'),
        ),
    ]
