# Generated by Django 5.2.11 on 2026-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_discount_end_date_course_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الوصول'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='has_lifetime_access',
            field=models.BooleanField(default=True, verbose_name='وصول مدى الحياة'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'has_lifetime_access'], name='courses_enr_user_id_07fb88_idx'),
        ),
    ]
